# Generated by Django 4.2.7 on 2026-04-17 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsmetaSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('workspace_id', models.UUIDField()),
                ('ismeta_version_id', models.UUIDField()),
                ('payload', models.JSONField(help_text='Полный JSON snapshot сметы из ISMeta')),
                ('status', models.CharField(choices=[('received', 'Получен'), ('processing', 'Обрабатывается'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='received', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ismeta_snapshot',
                'ordering': ['-created_at'],
            },
        ),
    ]
