# Generated by Django 4.2.7 on 2026-02-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_remove_mountingproposal_mounting_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalproposal',
            name='due_date',
            field=models.DateField(blank=True, help_text='Крайний срок, к которому ТКП должно быть выдано Заказчику', null=True, verbose_name='Дата выдачи ТКП'),
        ),
    ]
