# Generated by Django 4.2.7 on 2026-02-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0004_add_due_date_to_technical_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalproposal',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.CreateModel(
            name='TKPStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tkp_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('tkp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='proposals.technicalproposal', verbose_name='ТКП')),
            ],
            options={
                'verbose_name': 'История статусов ТКП',
                'verbose_name_plural': 'История статусов ТКП',
                'ordering': ['-changed_at'],
            },
        ),
    ]
