# Generated by Django 4.2.7 on 2026-02-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_invoice_source'),
        ('catalog', '0002_productworkmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices', to='payments.invoice', verbose_name='Счёт-источник'),
        ),
    ]
