# Generated by Django 4.2.7 on 2026-03-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productpricehistory_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='booklet_url',
            field=models.URLField(blank=True, verbose_name='Буклет (PDF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Список URL-ов изображений товара', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='manual_url',
            field=models.URLField(blank=True, verbose_name='Инструкция (PDF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, max_length=255, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='product',
            name='tech_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Словарь ТХ: {"Мощность": "2.5 кВт", ...}', verbose_name='Технические характеристики'),
        ),
    ]
