# Generated by Django 4.2.7 on 2026-03-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Например: Каталог WHEIL v23.1', max_length=255, verbose_name='Название каталога')),
                ('supplier_name', models.CharField(db_index=True, help_text='Латинское имя: galvent, wheil, и т.д.', max_length=100, verbose_name='Код поставщика')),
                ('pdf_file', models.FileField(upload_to='catalogs/suppliers/', verbose_name='PDF-файл каталога')),
                ('json_file', models.FileField(blank=True, upload_to='catalogs/suppliers/', verbose_name='JSON результат парсинга')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('detecting_toc', 'Анализ оглавления'), ('toc_ready', 'Оглавление готово'), ('parsing', 'Парсинг'), ('parsed', 'Разобран'), ('importing', 'Импорт в БД'), ('imported', 'Импортирован'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='Всего страниц')),
                ('sections', models.JSONField(blank=True, default=list, help_text='[{name, pages: [start, end], category_code, is_new_category, ...}]', verbose_name='Секции каталога')),
                ('current_section', models.PositiveIntegerField(default=0, verbose_name='Текущая секция')),
                ('total_sections', models.PositiveIntegerField(default=0, verbose_name='Всего секций')),
                ('current_batch', models.PositiveIntegerField(default=0, verbose_name='Текущий батч')),
                ('total_batches', models.PositiveIntegerField(default=0, verbose_name='Всего батчей')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='Товаров найдено')),
                ('variants_count', models.PositiveIntegerField(default=0, verbose_name='Вариантов найдено')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='Импортировано в БД')),
                ('categories_created', models.PositiveIntegerField(default=0, verbose_name='Создано категорий')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки парсинга')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='ID задачи Celery')),
            ],
            options={
                'verbose_name': 'Каталог поставщика',
                'verbose_name_plural': 'Каталоги поставщиков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_product_status_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_product_brand_idx',
        ),
        migrations.RemoveIndex(
            model_name='productpricehistory',
            name='catalog_pph_cp_product_idx',
        ),
    ]
