# Generated by Django 4.2.7 on 2026-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_knowledge_and_default_work_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productknowledge',
            name='public_source',
            field=models.BooleanField(default=False, verbose_name='Из публичного портала'),
        ),
        migrations.AddField(
            model_name='productworkmapping',
            name='public_source',
            field=models.BooleanField(default=False, verbose_name='Из публичного портала'),
        ),
    ]
