# Generated by Django 5.1.15 on 2026-04-17 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_create_workspace_and_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(default='шт', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('equipment_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('material_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('work_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('equipment_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('material_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('work_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('version', models.PositiveIntegerField(default=1)),
                ('match_source', models.CharField(choices=[('manual', 'Вручную'), ('history', 'История'), ('pricelist', 'Прайс-лист'), ('knowledge', 'База знаний'), ('category', 'Категория'), ('fuzzy', 'Fuzzy'), ('llm', 'LLM'), ('web', 'Web'), ('supplier', 'Поставщик'), ('unmatched', 'Не подобрано')], default='unmatched', max_length=16)),
                ('material_markup', models.JSONField(blank=True, null=True)),
                ('work_markup', models.JSONField(blank=True, null=True)),
                ('tech_specs', models.JSONField(blank=True, default=dict)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_key_equipment', models.BooleanField(default=False)),
                ('procurement_status', models.CharField(choices=[('none', '—'), ('requested', 'Запрошено'), ('quoted', 'КП получено'), ('booked', 'Забронировано'), ('ordered', 'Заказано')], default='none', max_length=16)),
                ('man_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estimate_item',
                'ordering': ['sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_name', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('ready', 'Готова'), ('transmitted', 'Передана в ERP'), ('archived', 'Архив')], default='draft', max_length=16)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('default_material_markup', models.JSONField(blank=True, default=dict, help_text='MarkupConfig JSON, e.g. {"type":"percent","value":30}')),
                ('default_work_markup', models.JSONField(blank=True, default=dict, help_text='MarkupConfig JSON, e.g. {"type":"percent","value":300}')),
                ('total_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_materials', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_works', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('man_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profitability_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('estimated_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='estimate.estimate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='workspace.workspace')),
            ],
            options={
                'db_table': 'estimate',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('material_markup', models.JSONField(blank=True, null=True)),
                ('work_markup', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='estimate.estimate')),
                ('parent_version_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimate.estimatesection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                'db_table': 'estimate_section',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['workspace', 'status'], name='idx_estimate_ws_status'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['workspace', 'created_at'], name='idx_estimate_ws_created'),
        ),
        # --- EstimateItem: HASH partitioning по workspace_id (ADR-0021) ---
        # managed=False на модели → Django не создаёт таблицу.
        # Таблица создаётся вручную через RunSQL с PARTITION BY HASH.
        migrations.RunSQL(
            sql="""
            CREATE TABLE estimate_item (
                id UUID NOT NULL DEFAULT gen_random_uuid(),
                section_id UUID NOT NULL REFERENCES estimate_section(id) ON DELETE CASCADE,
                estimate_id UUID NOT NULL REFERENCES estimate(id) ON DELETE CASCADE,
                workspace_id UUID NOT NULL REFERENCES workspace(id) ON DELETE CASCADE,
                row_id UUID NOT NULL DEFAULT gen_random_uuid(),
                sort_order INTEGER NOT NULL DEFAULT 0,
                name VARCHAR(500) NOT NULL,
                unit VARCHAR(50) NOT NULL DEFAULT 'шт',
                quantity NUMERIC(14,4) NOT NULL DEFAULT 0,
                equipment_price NUMERIC(19,2) NOT NULL DEFAULT 0,
                material_price NUMERIC(19,2) NOT NULL DEFAULT 0,
                work_price NUMERIC(19,2) NOT NULL DEFAULT 0,
                equipment_total NUMERIC(19,2) NOT NULL DEFAULT 0,
                material_total NUMERIC(19,2) NOT NULL DEFAULT 0,
                work_total NUMERIC(19,2) NOT NULL DEFAULT 0,
                total NUMERIC(19,2) NOT NULL DEFAULT 0,
                version INTEGER NOT NULL DEFAULT 1,
                source_item_id UUID,
                match_source VARCHAR(16) NOT NULL DEFAULT 'unmatched',
                material_markup JSONB,
                work_markup JSONB,
                tech_specs JSONB NOT NULL DEFAULT '{}',
                custom_data JSONB NOT NULL DEFAULT '{}',
                is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                is_key_equipment BOOLEAN NOT NULL DEFAULT FALSE,
                procurement_status VARCHAR(16) NOT NULL DEFAULT 'none',
                man_hours NUMERIC(10,2) NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, workspace_id)
            ) PARTITION BY HASH (workspace_id);

            -- 16 партиций (ADR-0021: покрывает рост до SaaS)
            CREATE TABLE estimate_item_p00 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 0);
            CREATE TABLE estimate_item_p01 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 1);
            CREATE TABLE estimate_item_p02 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 2);
            CREATE TABLE estimate_item_p03 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 3);
            CREATE TABLE estimate_item_p04 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 4);
            CREATE TABLE estimate_item_p05 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 5);
            CREATE TABLE estimate_item_p06 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 6);
            CREATE TABLE estimate_item_p07 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 7);
            CREATE TABLE estimate_item_p08 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 8);
            CREATE TABLE estimate_item_p09 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 9);
            CREATE TABLE estimate_item_p10 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 10);
            CREATE TABLE estimate_item_p11 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 11);
            CREATE TABLE estimate_item_p12 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 12);
            CREATE TABLE estimate_item_p13 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 13);
            CREATE TABLE estimate_item_p14 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 14);
            CREATE TABLE estimate_item_p15 PARTITION OF estimate_item FOR VALUES WITH (MODULUS 16, REMAINDER 15);

            -- Индексы
            CREATE INDEX idx_item_ws_estimate_sort ON estimate_item (workspace_id, estimate_id, sort_order);
            CREATE INDEX idx_item_row_id ON estimate_item (row_id);
            CREATE INDEX idx_item_ws_deleted ON estimate_item (workspace_id, is_deleted);
            """,
            reverse_sql="DROP TABLE IF EXISTS estimate_item CASCADE;",
        ),
    ]
