# Generated by Django 5.1.15 on 2026-04-17 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_create_estimate_section_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('pattern', models.CharField(max_length=500)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('regex', 'Regex'), ('exact', 'Exact')], default='contains', max_length=16)),
                ('work_name', models.CharField(max_length=500)),
                ('work_unit', models.CharField(default='шт', max_length=50)),
                ('work_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('confidence', models.DecimalField(decimal_places=2, default='0.85', max_digits=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_knowledge',
                'indexes': [models.Index(fields=['workspace_id', 'is_active'], name='idx_pk_ws_active')],
            },
        ),
    ]
