# Generated by Django 5.1.15 on 2026-04-17 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_create_product_knowledge'),
        ('workspace', '0001_create_workspace_and_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotTransmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sending', 'Отправляется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('retrying', 'Повтор')], default='pending', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='estimate.estimate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                'db_table': 'snapshot_transmission',
                'ordering': ['-created_at'],
            },
        ),
    ]
