# Generated by Django 4.2.7 on 2026-03-13 08:42

from django.db import migrations, models
import estimates.models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_estimateitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to=estimates.models.project_file_path, verbose_name='Файл проекта'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['section', 'sort_order'], name='estimates_e_section_85a2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['estimate', 'sort_order'], name='estimates_e_estimat_28dd32_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['subsection'], name='estimates_e_subsect_9460f3_idx'),
        ),
    ]
