# Generated by Django 4.2.7 on 2026-03-13 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estimates', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='column_config',
            field=models.JSONField(blank=True, default=list, help_text='Список определений столбцов. Пустой список = дефолтные столбцы.', verbose_name='Конфигурация столбцов'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Ключ = key столбца из column_config, значение = строковое представление.', verbose_name='Данные пользовательских столбцов'),
        ),
        migrations.CreateModel(
            name='ColumnConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('column_config', models.JSONField(default=list, verbose_name='Конфигурация столбцов')),
                ('is_default', models.BooleanField(default=False, verbose_name='Шаблон по умолчанию')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_config_templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Шаблон столбцов',
                'verbose_name_plural': 'Шаблоны столбцов',
                'ordering': ['-created_at'],
            },
        ),
    ]
