# Generated by Django 4.2.7 on 2026-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_specificationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Наименование товара / работы'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='original_name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Оригинальное наименование из спецификации'),
        ),
        migrations.AlterField(
            model_name='specificationitem',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Наименование'),
        ),
    ]
