# Generated by Django 5.1.15 on 2026-04-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_event',
            },
        ),
    ]
