# Generated by Django 4.2.7 on 2026-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Автоматически генерируется из `logo` (recolor monochromatic → white). Пусто для цветных логотипов — фронт использует оригинал.', null=True, upload_to='ac_rating/brands/dark/', verbose_name='Логотип (тёмная тема)'),
        ),
    ]
