# Generated by Django 4.2.7 on 2026-03-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0010_alter_counterparty_type'),
        ('catalog', '0004_product_rich_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('external_id', models.IntegerField(verbose_name='ID в API поставщика')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image_url', models.URLField(blank=True, verbose_name='Логотип')),
                ('website_url', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Бренд поставщика',
                'verbose_name_plural': 'Бренды поставщиков',
            },
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('external_id', models.IntegerField(verbose_name='ID в API поставщика')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('parent_external_id', models.IntegerField(blank=True, null=True, verbose_name='ID родителя в API')),
            ],
            options={
                'verbose_name': 'Категория поставщика',
                'verbose_name_plural': 'Категории поставщиков',
            },
        ),
        migrations.CreateModel(
            name='SupplierIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('provider', models.CharField(choices=[('breez', 'Бриз')], max_length=20, verbose_name='Провайдер')),
                ('base_url', models.URLField(verbose_name='URL API')),
                ('auth_header', models.CharField(help_text='Полный заголовок, например: Basic aGVycj...', max_length=500, verbose_name='Authorization header')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('last_catalog_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхр. каталога')),
                ('last_stock_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхр. остатков')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_integrations', to='accounting.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Интеграция поставщика',
                'verbose_name_plural': 'Интеграции поставщиков',
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('external_id', models.IntegerField(help_text='product_id из API поставщика', verbose_name='ID товара в API')),
                ('nc_code', models.CharField(db_index=True, help_text='Уникальный код товара у поставщика (например НС-1234567)', max_length=50, verbose_name='НС-код')),
                ('articul', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Артикул')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('series', models.CharField(blank=True, max_length=255, verbose_name='Серия')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Закупочная цена')),
                ('base_price_currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта закупочной цены')),
                ('ric_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Рекомендованная интернет-цена')),
                ('ric_price_currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта РИЦ')),
                ('for_marketplace', models.BooleanField(default=False, verbose_name='Для маркетплейсов')),
                ('images', models.JSONField(blank=True, default=list, help_text='Список URL-ов изображений', verbose_name='Изображения')),
                ('booklet_url', models.URLField(blank=True, verbose_name='Буклет (PDF)')),
                ('manual_url', models.URLField(blank=True, verbose_name='Инструкция (PDF)')),
                ('tech_specs', models.JSONField(blank=True, default=dict, verbose_name='Технические характеристики')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('price_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Цены обновлены')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supplier_integrations.supplierbrand', verbose_name='Бренд')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier_integrations.supplierintegration', verbose_name='Интеграция')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='catalog.product', verbose_name='Наш товар')),
                ('supplier_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supplier_integrations.suppliercategory', verbose_name='Категория поставщика')),
            ],
            options={
                'verbose_name': 'Товар поставщика',
                'verbose_name_plural': 'Товары поставщиков',
            },
        ),
        migrations.CreateModel(
            name='SupplierSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sync_type', models.CharField(choices=[('catalog_full', 'Полный импорт каталога'), ('stock_sync', 'Синхронизация остатков/цен')], max_length=20, verbose_name='Тип синхронизации')),
                ('status', models.CharField(choices=[('started', 'Запущено'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='started', max_length=20, verbose_name='Статус')),
                ('items_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано')),
                ('items_created', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('items_updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('items_errors', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='Детали ошибок')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='supplier_integrations.supplierintegration', verbose_name='Интеграция')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизаций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='supplier_integrations.supplierintegration', verbose_name='Интеграция'),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='our_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_categories', to='catalog.category', verbose_name='Наша категория'),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='supplier_integrations.suppliercategory', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='supplierbrand',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='supplier_integrations.supplierintegration', verbose_name='Интеграция'),
        ),
        migrations.CreateModel(
            name='SupplierStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('warehouse_name', models.CharField(max_length=255, verbose_name='Склад')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='supplier_integrations.supplierproduct', verbose_name='Товар поставщика')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складах',
                'unique_together': {('supplier_product', 'warehouse_name')},
            },
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['integration', 'is_active'], name='supplier_in_integra_cbccb8_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['product'], name='supplier_in_product_d2552d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together={('integration', 'nc_code')},
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('integration', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierbrand',
            unique_together={('integration', 'external_id')},
        ),
    ]
