# Generated by Django 4.2.7 on 2026-04-14 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0011_counterparty_is_public'),
        ('estimates', '0011_estimate_external_user_estimate_public_source'),
        ('supplier_integrations', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер запроса')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('partial', 'Частичный ответ'), ('responded', 'Получены ответы'), ('applied', 'Применён'), ('closed', 'Закрыт')], default='draft', max_length=20, verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок ответа')),
                ('message', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
            ],
            options={
                'verbose_name': 'Запрос поставщику',
                'verbose_name_plural': 'Запросы поставщикам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('model_name', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('unit', models.CharField(default='шт', max_length=30, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Количество')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Позиция запроса',
                'verbose_name_plural': 'Позиции запроса',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRFQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('recognized', 'Распознан'), ('reviewed', 'Проверен')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='rfq_responses/%Y/%m/', verbose_name='Файл КП/счёта')),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок поставки (дней)')),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок действия (дней)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Ответ поставщика',
                'verbose_name_plural': 'Ответы поставщиков',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRFQResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за ед.')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Цена от поставщика',
                'verbose_name_plural': 'Цены от поставщиков',
            },
        ),
        migrations.AlterModelOptions(
            name='suppliercategory',
            options={'ordering': ['title'], 'verbose_name': 'Категория поставщика', 'verbose_name_plural': 'Категории поставщиков'},
        ),
        migrations.AlterModelOptions(
            name='supplierintegration',
            options={'ordering': ['name'], 'verbose_name': 'Интеграция поставщика', 'verbose_name_plural': 'Интеграции поставщиков'},
        ),
        migrations.RemoveIndex(
            model_name='supplierproduct',
            name='si_sp_integration_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierproduct',
            name='si_sp_base_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierstock',
            name='si_stock_sp_qty_idx',
        ),
        migrations.AddField(
            model_name='supplierrfqresponseitem',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier_integrations.supplierrfqresponse', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='supplierrfqresponseitem',
            name='rfq_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_items', to='supplier_integrations.supplierrfqitem', verbose_name='Позиция запроса'),
        ),
        migrations.AddField(
            model_name='supplierrfqresponse',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_responses', to='accounting.counterparty', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='supplierrfqresponse',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='supplier_integrations.supplierrfq', verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='supplierrfqitem',
            name='estimate_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_items', to='estimates.estimateitem', verbose_name='Строка сметы'),
        ),
        migrations.AddField(
            model_name='supplierrfqitem',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier_integrations.supplierrfq', verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='counterparties',
            field=models.ManyToManyField(blank=True, related_name='rfqs', to='accounting.counterparty', verbose_name='Поставщики'),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rfqs', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='estimates.estimate', verbose_name='Смета'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierrfqresponseitem',
            unique_together={('response', 'rfq_item')},
        ),
    ]
