# Generated by Django 4.2.7 on 2026-03-24 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('section', models.CharField(choices=[('dashboard', 'Пункт управления'), ('commercial', 'Коммерческие предложения'), ('objects', 'Объекты'), ('finance', 'Финансы'), ('contracts', 'Договоры'), ('supply', 'Снабжение и Склад'), ('goods', 'Товары и услуги'), ('pto', 'ПТО'), ('marketing', 'Маркетинг'), ('communications', 'Переписка'), ('settings', 'Справочники и Настройки'), ('help', 'Справка')], db_index=True, max_length=30, verbose_name='Раздел')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст замечания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решён')], default='new', max_length=20, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Замечание',
                'verbose_name_plural': 'Замечания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст ответа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_replies', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='section_feedback.sectionfeedback', verbose_name='Замечание')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.ImageField(upload_to='section_feedback/%Y/%m/', verbose_name='Файл')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='section_feedback.sectionfeedback', verbose_name='Замечание')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='section_feedback.feedbackreply', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sectionfeedback',
            index=models.Index(fields=['section', '-created_at'], name='section_fee_section_ad436f_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionfeedback',
            index=models.Index(fields=['status'], name='section_fee_status_2e5619_idx'),
        ),
    ]
