# Generated by Django 4.2.7 on 2026-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_feedback', '0002_add_hvac_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionfeedback',
            name='section',
            field=models.CharField(choices=[('dashboard', 'Пункт управления'), ('commercial', 'Коммерческие предложения'), ('estimates', 'Сметы'), ('objects', 'Объекты'), ('finance', 'Финансы'), ('contracts', 'Договоры'), ('supply', 'Снабжение и Склад'), ('goods', 'Товары и услуги'), ('pto', 'ПТО'), ('marketing', 'Маркетинг'), ('communications', 'Переписка'), ('settings', 'Справочники и Настройки'), ('hvac', 'HVAC-новости'), ('help', 'Справка')], db_index=True, max_length=30, verbose_name='Раздел'),
        ),
    ]
