# Generated by Django 4.2.7 on 2026-03-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0007_workitem_required_grade_alter_workitem_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ['section', 'sort_order', 'article'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AddField(
            model_name='workitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок из Excel файла для правильной последовательности', verbose_name='Порядок сортировки'),
        ),
    ]
