# Generated by Django 4.2.7 on 2026-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0008_add_workitem_sort_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['is_current', 'section'], name='workitem_current_section_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['article'], name='workitem_article_idx'),
        ),
    ]
