# Generated by Django 4.2.7 on 2026-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_create_system_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('bitrix', 'Из Битрикс24'), ('manual', 'Ручной ввод'), ('recurring', 'Периодический'), ('bulk_import', 'Массовый импорт')], default='manual', max_length=20, verbose_name='Источник'),
        ),
    ]
