# Generated by Django 4.2.7 on 2026-02-27 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0014_alter_invoice_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('processing', 'Обработка'), ('completed', 'Завершено'), ('completed_with_errors', 'Завершено с ошибками')], default='processing', max_length=30, verbose_name='Статус')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='Всего файлов')),
                ('processed_files', models.PositiveIntegerField(default=0, verbose_name='Обработано')),
                ('successful', models.PositiveIntegerField(default=0, verbose_name='Успешно')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='С ошибками')),
                ('skipped_duplicate', models.PositiveIntegerField(default=0, verbose_name='Пропущено (дубликаты)')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_import_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сессия массового импорта',
                'verbose_name_plural': 'Сессии массового импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='bulk_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.bulkimportsession', verbose_name='Сессия массового импорта'),
        ),
    ]
