# Generated by Django 4.2.7 on 2026-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_bulk_import_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('recognition', 'Распознаётся'), ('review', 'На проверке'), ('verified', 'Проверен'), ('in_registry', 'В реестре'), ('approved', 'Одобрен'), ('sending', 'Отправляется в банк'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='recognition', max_length=20, verbose_name='Статус'),
        ),
    ]
