# Generated by Django 4.2.7 on 2026-02-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_estimateitem'),
        ('payments', '0016_add_verified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estimate',
            field=models.ForeignKey(blank=True, help_text='Если заполнено — счёт для подбора цен сметчиком', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_invoices', to='estimates.estimate', verbose_name='Смета (ценовое исследование)'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['estimate', 'status'], name='payments_in_estimat_956e3b_idx'),
        ),
    ]
