# Generated by Django 4.2.7 on 2026-05-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HvacIsmetaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text="Включить публичный сайт ISMeta. False → пользователи видят 'Сервис временно недоступен'.")),
                ('default_pipeline', models.CharField(choices=[('main', 'Main (DeepSeek)'), ('td17g', 'TD-17g (Docling+Camelot+Vision hybrid)')], default='td17g', help_text='Дефолтный движок распознавания.', max_length=20)),
                ('default_llm_profile_id', models.IntegerField(blank=True, help_text='Soft-FK на llm_profile.id в ismeta-postgres (валидация на стороне UI).', null=True)),
                ('concurrency_limit_enabled', models.BooleanField(default=True, help_text='Ограничить 1 PDF одновременно с одной сессии.')),
                ('pdf_storage_path', models.CharField(default='/storage/ismeta-uploads/', help_text='Куда сервер копирует загруженные PDF.', max_length=500)),
                ('require_registration', models.BooleanField(default=False, help_text='Требовать регистрацию для доступа.')),
                ('max_file_size_mb', models.IntegerField(default=50, help_text='Лимит на размер PDF.')),
                ('feedback_email', models.EmailField(default='andrei@aug-clim.ru', help_text='Адрес для feedback из формы внизу страницы.', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки публичного ISMeta',
                'verbose_name_plural': 'Настройки публичного ISMeta',
                'db_table': 'hvac_ismeta_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='hvacismetasettings',
            constraint=models.CheckConstraint(check=models.Q(('pk', 1)), name='hvac_ismeta_settings_singleton'),
        ),
    ]
