# Generated by Django 4.2.7 on 2026-05-01 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hvac_ismeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsmetaJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('pdf_filename', models.CharField(max_length=255)),
                ('pdf_storage_path', models.CharField(max_length=500)),
                ('pdf_size_bytes', models.BigIntegerField()),
                ('pipeline', models.CharField(max_length=20)),
                ('llm_profile_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обработка'), ('done', 'Готово'), ('error', 'Ошибка'), ('cancelled', 'Отменено')], default='queued', max_length=20)),
                ('pages_total', models.IntegerField(default=0)),
                ('pages_processed', models.IntegerField(default=0)),
                ('items_count', models.IntegerField(default=0)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('feedback_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ISMeta job',
                'verbose_name_plural': 'ISMeta jobs',
                'db_table': 'hvac_ismeta_job',
                'indexes': [models.Index(fields=['session_key', 'status'], name='ismeta_job_session_status'), models.Index(fields=['created_at'], name='ismeta_job_created_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='IsmetaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='hvac_ismeta.ismetajob')),
            ],
            options={
                'verbose_name': 'ISMeta feedback',
                'verbose_name_plural': 'ISMeta feedback',
                'db_table': 'hvac_ismeta_feedback',
            },
        ),
    ]
