# Generated by Django 5.1.15 on 2026-04-17 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('task_type', models.CharField(max_length=32)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('tokens_in', models.IntegerField()),
                ('tokens_out', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latency_ms', models.IntegerField()),
                ('estimate_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'llm_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace_id', 'created_at'], name='idx_llm_usage_ws_created')],
            },
        ),
    ]
