# Generated by Django 4.2.7 on 2026-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_rating_run_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='anthropic_input_price',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Anthropic Input Price'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='anthropic_model',
            field=models.CharField(default='claude-haiku-4-5', max_length=50, verbose_name='Anthropic Model'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='anthropic_output_price',
            field=models.DecimalField(decimal_places=4, default=5.0, max_digits=10, verbose_name='Anthropic Output Price'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='gemini_input_price',
            field=models.DecimalField(decimal_places=4, default=0.3, max_digits=10, verbose_name='Gemini Input Price'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='gemini_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=50, verbose_name='Gemini Model'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='gemini_output_price',
            field=models.DecimalField(decimal_places=4, default=2.5, max_digits=10, verbose_name='Gemini Output Price'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='grok_input_price',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=10, verbose_name='Grok Input Price'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='grok_output_price',
            field=models.DecimalField(decimal_places=4, default=0.5, max_digits=10, verbose_name='Grok Output Price'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='openai_input_price',
            field=models.DecimalField(decimal_places=4, default=0.4, max_digits=10, verbose_name='OpenAI Input Price'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='openai_model',
            field=models.CharField(default='gpt-4.1-mini', max_length=50, verbose_name='OpenAI Model'),
        ),
        migrations.AlterField(
            model_name='ratingconfiguration',
            name='openai_output_price',
            field=models.DecimalField(decimal_places=4, default=1.6, max_digits=10, verbose_name='OpenAI Output Price'),
        ),
    ]
