# Generated by Django 4.2.7 on 2026-04-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_newspost_mentioned_ac_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок отображения в UI.', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Отключённые категории не показываются в picker, но FK на существующих новостях сохраняется (soft-delete).', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='newspost',
            name='category_ref',
            field=models.ForeignKey(blank=True, db_column='category_ref_slug', help_text="FK-вариант category для CRUD-управления разделами. Синхронизируется с CharField 'category' в save(). CharField будет удалён отдельным эпиком.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='news.newscategory', to_field='slug', verbose_name='Category (FK)'),
        ),
    ]
